services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB_USERNAME} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20

  ml:
    image: tax-refund-ml:latest
    build:
      context: ./ml
    environment:
      ML_DB_URL: postgresql+psycopg2://${POSTGRES_DB_USERNAME}:${POSTGRES_DB_PASSWORD}@${POSTGRES_HOST_ML}:5432/${POSTGRES_DB}
      ML_MODEL_PATH: /models/eta_model.joblib
      ML_MODEL_META_PATH: /models/eta_model_meta.json
    ports:
      - "8000:8000"


  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_DB_URL: ${POSTGRES_DB_URL}
      POSTGRES_DB_USERNAME: ${POSTGRES_DB_USERNAME}
      POSTGRES_DB_PASSWORD: ${POSTGRES_DB_PASSWORD}
      APP_SECURITY_JWT_SECRET: ${APP_SECURITY_JWT_SECRET}
      APP_SECURITY_JWT_ISSUER: ${APP_SECURITY_JWT_ISSUER}
      AI_PROVIDER: ${AI_PROVIDER}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-}
    ports:
      - "${BACKEND_PORT}:8080"
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
